version: '3.8'

# 🚀 Универсальная конфигурация Gongbu Platform
# Работает как локально, так и на VPS
# Использует переменные среды из .env файла

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gongbu_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gongbu_network

  # Redis для кеширования
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_dev}
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_dev}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis_dev}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gongbu_network

  # Auth Service (микросервис аутентификации)
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_auth_service
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gongbu_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Course Service (микросервис курсов)
  course-service:
    build:
      context: ./services/course-service
      dockerfile: Dockerfile.dev
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_course_service
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gongbu_network
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bot Service (Telegram бот)
  bot-service:
    build:
      context: ./services/bot-service
      dockerfile: Dockerfile.dev
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_bot_service
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3003
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - COURSE_SERVICE_URL=http://course-service:3002
      - AUTH_SERVICE_URL=http://auth-service:3001
      - REDIS_URL=${REDIS_URL}
      - WEBAPP_URL=${WEBAPP_URL}
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      course-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gongbu_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web App (React фронтенд)
  web-app:
    build:
      context: ./apps/web-app
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_web_app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=${API_BASE_URL}
      - VITE_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - VITE_WEBAPP_URL=${WEBAPP_URL}
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - course-service
      - bot-service
    restart: unless-stopped
    networks:
      - gongbu_network
    # В development режиме для hot reload можно подмонтировать исходный код
    # volumes:
    #   - ./apps/web-app/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-gongbu}_nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      # Динамический выбор конфигурации nginx в зависимости от среды
      - ./${NGINX_CONFIG:-nginx.local.conf}:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./uploads:/app/uploads:ro
      # SSL сертификаты (только для production)
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      web-app:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      course-service:
        condition: service_healthy
      bot-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gongbu_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  uploads:
    driver: local

networks:
  gongbu_network:
    driver: bridge
