name: 🐛 Bug Report
description: Сообщить об ошибке в Gongbu Platform
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Пожалуйста, заполните форму ниже.

  - type: textarea
    id: bug-description
    attributes:
      label: Описание ошибки
      description: Четкое и краткое описание ошибки
      placeholder: Опишите, что произошло...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Шаги для воспроизведения
      description: Шаги для воспроизведения поведения
      placeholder: |
        1. Перейти к '...'
        2. Нажать на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Четкое и краткое описание того, что вы ожидали
      placeholder: Опишите, что должно было произойти...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Фактическое поведение
      description: Четкое и краткое описание того, что произошло на самом деле
      placeholder: Опишите, что произошло на самом деле...
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Затронутый сервис
      description: Какой сервис затронут?
      options:
        - Web App (Frontend)
        - Auth Service
        - Course Service
        - Bot Service
        - Payment Service
        - Notification Service
        - API Gateway
        - Infrastructure
        - Документация
        - Другое
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Серьезность
      description: Насколько критична эта ошибка?
      options:
        - 🔴 Critical (система не работает)
        - 🟠 High (основная функциональность нарушена)
        - 🟡 Medium (частичная функциональность нарушена)
        - 🟢 Low (незначительная проблема)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Окружение
      description: Информация об окружении
      placeholder: |
        - ОС: [например, Ubuntu 20.04]
        - Браузер: [например, Chrome 91]
        - Node.js версия: [например, 20.x]
        - Docker версия: [например, 24.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Логи и скриншоты
      description: Добавьте логи, скриншоты или другие файлы, которые помогут объяснить проблему
      placeholder: Вставьте логи или опишите, где их найти...

  - type: textarea
    id: additional-context
    attributes:
      label: Дополнительный контекст
      description: Добавьте любой другой контекст о проблеме здесь
      placeholder: Любая дополнительная информация...
